
sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-sitemap

title: "John Quan"
tagline: "Tech, Gear, Photography, & Everything Else"
email: ""
description: >- # this means to ignore newlines until "baseurl:"
author: name
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: UA-xxxxxxxx-x
twitter:
  username: 
  card: summary #keep this to generate a twitter share card
cdnBaseUrl: /dev_cdn/
permalink: /:title/

# Research config file if/then condition placed in config file. Purpose, if dev = use local dir; if prod = use bunnyCdn